version: '3.7'

services:
  db:
    image: postgres:16.3
    restart: 'unless-stopped'
    environment:
      - POSTGRES_DATABASE=${PG_DATABASE}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    container_name: delivery-db
    volumes:
      - './db_data:/var/www/api/postgresql/data'
    networks:
        - 'delivery_network'
    ports:
      - '5432:5432'
      
  backend:
    container_name: 'delivery-back'
    restart: 'unless-stopped'
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    depends_on: 
      - db
    networks:
      - 'delivery_network'
    ports: 
      - '8080:${APP_PORT}'
    volumes: 
        - './:/var/www/api'

networks:
  delivery_network:
    external: true